version: 2.1

jobs:
  build:
    machine: true
    resource_class: 2xlarge
    steps:
      - checkout
      - run: nproc
      - run: lscpu
    parallelism: 1

workflows:
  version: 2
  all:
    jobs:
      - build
